POST http://localhost:3000/actors/
content-type: application/json 

{
  "first_name": "a",
  "last_name": "b",
  "age": "2"
}

### 

GET http://localhost:3000/movies/


### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Randy Yiv",
  "email": "randyyiv@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### movie_genre create 

GET http://localhost:3000/movie_genres?movie_id=2&genre_id=4